### ISSUE TITLE
How would I add a new library?

### ISSUE THREAD

**Issue by soypat** [lesismal/go-websocket-benchmark#14]
Lib in question: https://github.com/soypat/peasocket

**Comment by lxzan** [comment]
star, fork and create pr

**Comment by lesismal** [comment]
And please make sure that there's no problem as gobwas+poller has or similar problems, related:
https://github.com/lesismal/go-websocket-benchmark/pull/12

@lxzan  Before mereged, we need to review and test by some tunnel to simulate TCP sticky packet.

**Comment by soypat** [comment]
OK, I've made a PR. Do I really have to make those low level changes to the network to test the benchmark out? Is there a way to just smoke test it without going through the certification of the environment?

**Comment by lxzan** [comment]
modifying ulimit alone is sufficient
