### ISSUE TITLE
Choose the latest version of gobwas/ws for a fair compare

### ISSUE THREAD

**Issue by WeiquanWa** [lesismal/go-websocket-benchmark#2]
I've noticed  gobwas/ws:v1.0.2 is being used for benchmarking. but the latest version of the library is v1.2.1.

**Comment by lesismal** [comment]
Thanks for the correction!
Already update to v1.2.1:
https://github.com/lesismal/go-websocket-benchmark/blob/main/go.mod#L6

I haven't update the output in README, but have run the benchmark and it seems gobwas/ws v1.2.1 brings no performance promotion.
