### ISSUE TITLE
lost some test result in README

### ISSUE THREAD

**Issue by futurist** [lesismal/go-websocket-benchmark#7]
I've noticed `hertz` in frameworks folder, but don't have it's result in README

**Comment by lesismal** [comment]
We met some problems with hertz, such as connect timeout:
![image](https://github.com/lesismal/go-websocket-benchmark/assets/40462947/3a6a6e53-4949-47e4-b511-579571951ac6)

May update the result in README after we found the reason.

You can just run the benchmark yourself to see the result.

**Comment by lxzan** [comment]
The values are for reference only, but the general direction is accurate.

|      Framework       | Conns | Payload |  Total  | Success | Failed | Used  | CPU Avg | MEM Avg |   Avg   |  TPS   |  TP50   |  TP90   |  TP99   |
|      ---             |  ---  |   ---   |   ---   |   ---   |  ---   |  ---  |   ---   |   ---   |   ---   |  ---   |   ---   |   ---   |   ---   |
|     fasthttp         | 10000 |  1024   | 1000000 | 1000000 |   0    | 4.17s | 243.81% | 263.53M | 8.34ms  | 239561 | 8.08ms  | 13.44ms | 20.47ms |
|     gobwas           | 10000 |  1024   | 1000000 | 1000000 |   0    | 5.76s | 328.10% | 83.78M  | 11.50ms | 173633 | 11.01ms | 18.25ms | 28.49ms |
|     gorilla          | 10000 |  1024   | 1000000 | 1000000 |   0    | 4.31s | 252.99% | 337.07M | 8.61ms  | 232188 | 8.30ms  | 13.81ms | 20.77ms |
|      gws             | 10000 |  1024   | 1000000 | 1000000 |   0    | 4.09s | 228.69% | 233.08M | 8.17ms  | 244340 | 7.99ms  | 13.01ms | 18.84ms |
| gws_basedon_stdhttp  | 10000 |  1024   | 1000000 | 1000000 |   0    | 4.21s | 239.85% | 280.22M | 8.42ms  | 237383 | 8.08ms  | 13.55ms | 20.91ms |
|      hertz           | 10000 |  1024   | 1000000 | 1000000 |   0    | 5.27s | 271.04% | 499.33M | 10.51ms | 189881 | 9.97ms  | 15.83ms | 22.18ms |
| nbio_basedon_stdhttp | 10000 |  1024   | 1000000 | 1000000 |   0    | 4.47s | 250.96% | 179.89M | 8.93ms  | 223768 | 8.58ms  | 14.28ms | 21.20ms |
|  nbio_mod_blocking   | 10000 |  1024   | 1000000 | 1000000 |   0    | 4.45s | 253.36% | 169.74M | 8.89ms  | 224644 | 8.60ms  | 14.12ms | 21.44ms |
|   nbio_mod_mixed     | 10000 |  1024   | 1000000 | 1000000 |   0    | 4.52s | 258.76% | 187.40M | 9.03ms  | 221302 | 8.64ms  | 14.38ms | 22.85ms |
| nbio_mod_nonblocking | 10000 |  1024   | 1000000 | 1000000 |   0    | 5.02s | 242.35% | 68.47M  | 10.04ms | 199011 | 9.52ms  | 15.22ms | 22.23ms |
|     nhooyr           | 10000 |  1024   | 1000000 | 1000000 |   0    | 6.32s | 303.34% | 541.12M | 12.61ms | 158198 | 11.16ms | 20.13ms | 42.52ms |

**Comment by lesismal** [comment]
README updated, with hertz both based on netpoll and std included. 

Different env and benchmark input, different results.
So, I'd suggest running the code in yourself's env, rather than believing the results in my env.
